# Generated by Django 4.1.7 on 2023-04-04 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'AllCategories',
            },
        ),
        migrations.CreateModel(
            name='NewArrivals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('Price', models.FloatField(default=200)),
                ('Code', models.CharField(max_length=20)),
                ('Description', models.CharField(max_length=200)),
                ('images', models.ImageField(default='abc.jpg', upload_to='images')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.allcategories')),
            ],
            options={
                'db_table': 'NewArrivals',
            },
        ),
    ]
