# Generated by Django 4.1.7 on 2024-06-11 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newarrivals',
            name='Price',
        ),
    ]
