# Generated by Django 4.1.7 on 2023-04-04 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_remove_userinfo_id_alter_userinfo_uname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='uname',
            new_name='username',
        ),
    ]
