# Generated by Django 4.1.7 on 2024-06-11 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_mycart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mycart',
            old_name='qty',
            new_name='Available',
        ),
        migrations.RemoveField(
            model_name='mycart',
            name='items',
        ),
    ]
